import type { BioDataField, BioDataFormData } from "./bio-data-types";

export const defaultBioDataForm: BioDataFormData = {
  memberNo: "",
  familyNo: "",
  surname: "",
  firstName: "",
  otherNames: "",
  dob: "",
  occupation: "",
  idPpNo: "",
  bloodGroup: "",
  relationToPrincipal: "1",
  userId: "",
  dateEntered: "",
  familyTitle: "1",
  dealingUser: "",
  cancelled: "",
  employmentNo: "",
  gender: "",
  cardToMember: "",
  passportNo: "",
  nhifCardNo: "",
  height: "",
  weight: "",
  photoNForm: "",
  photoNo: "",
  infoToPrinter: "",
  cardFromPrinter: "",
  appFormDate: "",
  maritalStatus: "",
  dateEmployed: "",
  depPos: "",
  corpId: "",
  mobileNo: "",
  emailAdd: "",
};

export const bioDataFields: BioDataField[] = [
  { name: "corpId", label: "Corporate" },
  { name: "familyNo", label: "Family No" },
  { name: "memberNo", label: "Member No" },
  { name: "idPpNo", label: "National ID or Passport No." },
  { name: "employmentNo", label: "Employment No" },
  { name: "surname", label: "Surname" },
  { name: "firstName", label: "First Name" },
  { name: "otherNames", label: "Other Names" },
  { name: "dob", label: "Date of Birth *", type: "date", required: true },
  { name: "familyTitle", label: "Family Title" },
  { name: "gender", label: "Gender *", required: true },
  { name: "bloodGroup", label: "Blood Group" },
  { name: "relationToPrincipal", label: "Relationship to Principal" },
  { name: "depPos", label: "Dep Pos", type: "number" },
  { name: "occupation", label: "Occupation" },
  { name: "photoNForm", label: "Photo Availed" },
  { name: "infoToPrinter", label: "Date to Printer", type: "date" },
  { name: "cardFromPrinter", label: "Date from Printer", type: "date" },
  { name: "cardToMember", label: "Date to Member", type: "date" },
  { name: "maritalStatus", label: "Marital Status", type: "number" },
  { name: "passportNo", label: "Passport No" },
  { name: "nhifCardNo", label: "NHIF Card No" },
  { name: "height", label: "Height" },
  { name: "weight", label: "Weight" },
  { name: "dateEmployed", label: "Date Employed", type: "date" },
  { name: "mobileNo", label: "Mobile No" },
  { name: "emailAdd", label: "Email", type: "email" },
  { name: "cancelled", label: "Cancelled" },
  { name: "photoNo", label: "Photo No", type: "number" },
  { name: "appFormDate", label: "App Form Date", type: "date" },
  { name: "userId", label: "User ID" },
  { name: "dealingUser", label: "Dealing User" },
  { name: "dateEntered", label: "Date Entered", type: "date" },
];

export const bioDataFieldNames: (keyof BioDataFormData)[] = [
  "corpId",
  "familyNo",
  "memberNo",
  "idPpNo",
  "employmentNo",
  "surname",
  "firstName",
  "otherNames",
  "dob",
  "familyTitle",
  "gender",
  "bloodGroup",
  "relationToPrincipal",
  "occupation",
  "photoNForm",
  "infoToPrinter",
  "cardFromPrinter",
  "cardToMember",
];

export function getBioDataFields(names: (keyof BioDataFormData)[]): BioDataField[] {
  const byName = new Map(bioDataFields.map((field) => [field.name, field]));
  return names.flatMap((name) => {
    const field = byName.get(name);
    return field ? [field] : [];
  });
}
