import type { MedicalDetailsField, MedicalDetailsFormData } from "./medical-details-types";

export const defaultMedicalDetailsForm: MedicalDetailsFormData = {
  memberNo: "",
  anniv: "1",
  asthma: "",
  diabetes: "",
  hypertension: "",
  convulsionEpilepsy: "",
  gastricDuodenalUlcers: "",
  heartDisease: "",
  neurologicalDisease: "",
  currentlyIll: "",
  currentIllDetails: "",
  gallstones: "",
  recentConsultedDoc: "",
  recentConsultedDetails: "",
  disabled: "",
  disabilityDetails: "",
  pastDeliveries: "",
  normal: "",
  caesarian: "",
  expectant: "",
  expectedDeliveryDate: "",
  psychiatricIllness: "",
  recurrentTonsillitis: "",
  arthritisFibroids: "",
  menstrualDisorder: "",
  cancer: "",
  smokes: "",
  takesAlcohol: "",
  onRegularMedication: "",
  regularMedicationDetails: "",
  futureHospitalization: "",
  currentDoctor: "",
};

export const medicalDetailsFields = [
  { name: "memberNo", label: "Member No" },
  { name: "anniv", label: "Anniv *", type: "number", required: true },
  { name: "asthma", label: "Asthma" },
  { name: "diabetes", label: "Diabetic" },
  { name: "hypertension", label: "Hypertension" },
  { name: "convulsionEpilepsy", label: "Convulsion / Epilepsy" },
  { name: "gastricDuodenalUlcers", label: "Gastric / Duodenal Ulcers" },
  { name: "heartDisease", label: "Heart Disease" },
  { name: "neurologicalDisease", label: "Neurological Disease" },
  { name: "currentlyIll", label: "Currently Ill" },
  { name: "currentIllDetails", label: "Current Illness Details" },
  { name: "gallstones", label: "Gallstones" },
  { name: "recentConsultedDoc", label: "Recently Consulted Doctor" },
  { name: "recentConsultedDetails", label: "Consulted for?" },
  { name: "disabled", label: "Disabled" },
  { name: "disabilityDetails", label: "Disability Details" },
  { name: "pastDeliveries", label: "Past Deliveries", type: "number" },
  { name: "normal", label: "Normal Deliveries", type: "number" },
  { name: "caesarian", label: "Caesarian", type: "number" },
  { name: "expectant", label: "Expectant" },
  { name: "expectedDeliveryDate", label: "Expected Delivery Date", type: "date" },
  { name: "psychiatricIllness", label: "Psychiatric Illness" },
  { name: "recurrentTonsillitis", label: "Recurrent Tonsillitis" },
  { name: "arthritisFibroids", label: "Arthritis / Fibroids" },
  { name: "menstrualDisorder", label: "Menstrual Disorder" },
  { name: "cancer", label: "Cancer" },
  { name: "smokes", label: "Smokes" },
  { name: "takesAlcohol", label: "Takes Alcohol" },
  { name: "onRegularMedication", label: "On Regular Medication" },
  { name: "regularMedicationDetails", label: "Medication Details" },
  { name: "futureHospitalization", label: "Future Hospitalization" },
  { name: "currentDoctor", label: "Current Doctor" },
] satisfies MedicalDetailsField[];

export const medicalDetailsFieldNames: (keyof MedicalDetailsFormData)[] = [
  "memberNo",
  "anniv",
  "asthma",
  "diabetes",
  "cancer",
  "currentlyIll",
  "currentIllDetails",
  "recentConsultedDoc",
  "recentConsultedDetails",
  "onRegularMedication",
  "regularMedicationDetails",
  "disabled",
  "disabilityDetails",
  "expectant",
  "expectedDeliveryDate",
];

export function getMedicalDetailsFields(names: (keyof MedicalDetailsFormData)[]) {
  const byName = new Map(medicalDetailsFields.map((field) => [field.name, field]));
  return names
    .map((name) => byName.get(name))
    .filter((field): field is MedicalDetailsField => Boolean(field));
}
