-- CreateTable
CREATE TABLE "member_medical" (
    "member_no" VARCHAR(20) NOT NULL,
    "anniv" DECIMAL(2,0) NOT NULL,
    "asthma" DECIMAL(1,0),
    "diabetes" DECIMAL(1,0),
    "hypertension" DECIMAL(1,0),
    "convulsion_epilepsy" DECIMAL(1,0),
    "gastric_duodenal_ulcers" DECIMAL(1,0),
    "heart_disease" DECIMAL(1,0),
    "neurological_disease" DECIMAL(1,0),
    "currently_ill" DECIMAL(1,0),
    "current_ill_details" VARCHAR(30),
    "gallstones" DECIMAL(1,0),
    "recent_consulted_doc" DECIMAL(1,0),
    "recent_consulted_details" VARCHAR(30),
    "diabled" DECIMAL(1,0),
    "disability_details" VARCHAR(30),
    "past_deliveries" DECIMAL(2,0),
    "normal" DECIMAL(2,0),
    "caesarian" DECIMAL(2,0),
    "expectant" DECIMAL(1,0),
    "expected_delivery_date" DATE,
    "psychiatric_illness" DECIMAL(1,0),
    "recurrent_tonsillitis" DECIMAL(1,0),
    "arthritis_fibroids" DECIMAL(1,0),
    "menstrual_disorder" DECIMAL(1,0),
    "cancer" DECIMAL(1,0),
    "smokes" DECIMAL(1,0),
    "takes_alcohol" DECIMAL(1,0),
    "on_regular_medication" DECIMAL(1,0),
    "regular_medication_details" VARCHAR(30),
    "future_hospitalization" VARCHAR(30),
    "current_doctor" VARCHAR(30),

    CONSTRAINT "member_medical_pkey" PRIMARY KEY ("member_no","anniv")
);
