-- CreateTable
CREATE TABLE "bills" (
    "invoice_no" VARCHAR(30) NOT NULL,
    "claim_no" VARCHAR(20) NOT NULL,
    "claim_form_no" VARCHAR(15) NOT NULL,
    "provider" DECIMAL(5,0) NOT NULL,
    "member_no" VARCHAR(20) NOT NULL,
    "service" DECIMAL(10,0) NOT NULL,
    "claim_nature" DECIMAL(2,0) NOT NULL,
    "referred_by" DECIMAL(5,0),
    "ip_doctor" DECIMAL(5,0),
    "invoice_date" DATE NOT NULL,
    "invoiced_amount" DECIMAL(10,2) NOT NULL,
    "deduction_amount" DECIMAL(10,2),
    "deduction_reason" DECIMAL(5,0),
    "amount_payable" DECIMAL(10,2),
    "deduction_notes" VARCHAR(255),
    "paid" DECIMAL(1,0),
    "voucher_no" VARCHAR(10),
    "payment_no" VARCHAR(10),
    "sent_to_re" DECIMAL(1,0),
    "batch_no" VARCHAR(15),
    "payment_date" DATE,
    "user_id" VARCHAR(10),
    "date_entered" DATE,
    "refund" DECIMAL(1,0),
    "claimed_cancelled" DECIMAL(1,0),
    "anniv" DECIMAL(3,0),
    "capped" DECIMAL(1,0),
    "admin_fee" DECIMAL(10,2),
    "fund" DECIMAL(1,0),
    "re_insurer" DECIMAL(2,0),
    "date_received" DATE,
    "vet_status" DECIMAL(1,0),
    "entry_notes" VARCHAR(30),
    "voucher_user" VARCHAR(10),
    "bill_serial_no" VARCHAR(20),
    "contra_amt" DECIMAL(10,2),
    "corp_expense" DECIMAL(1,0),
    "pre_auth_no" DECIMAL(7,0),
    "voucher_date" DATE,
    "in_excess" DECIMAL(1,0),
    "excess_amt" DECIMAL(10,2),
    "excess_invoiced" DECIMAL(1,0),
    "excess_invoice_no" VARCHAR(10),
    "excess_repaid_amt" DECIMAL(10,2),
    "excess_receipt_no" VARCHAR(10),
    "corp_id" VARCHAR(10),
    "family_no" VARCHAR(20),
    "pri_dep" DECIMAL(2,0),
    "sub" DECIMAL(1,0),
    "admin_fee_rate" DECIMAL(5,2),
    "whtax" DECIMAL(10,2),
    "whtax_rate" DECIMAL(10,2),
    "product_code" DECIMAL(2,0),
    "loss_date" DATE,
    "excess_receipted" DECIMAL(1,0),
    "cheque_no" VARCHAR(15),
    "sub_limiter" DECIMAL(2,0),
    "authed" DECIMAL(1,0),
    "disc_amount" DECIMAL(15,2),
    "proxy_payee" VARCHAR(100),
    "reversed_claim" DECIMAL(1,0),
    "cheque_cancelled" DECIMAL(15,0),
    "initial_cheque" DECIMAL(15,0),
    "replaced_cheque" DECIMAL(15,0),
    "batched" DECIMAL(2,0),
    "stamped" DECIMAL(2,0),
    "claim_form" DECIMAL(2,0),
    "itemized" DECIMAL(2,0),
    "lou" DECIMAL(2,0),
    "notes" VARCHAR(50),
    "user_verified" VARCHAR(31),
    "time_barred" DECIMAL(2,0),
    "filled_claim_form" DECIMAL(1,0),
    "provider_reimbursement" DECIMAL(6,0),
    "cheque_discount" DECIMAL(15,2),
    "chq_disc_crt" VARCHAR(50),
    "filed" DECIMAL(15,0),
    "invoice_id" VARCHAR(30),
    "claim_id" VARCHAR(30),
    "id" VARCHAR(30),
    "claim_source" VARCHAR(30),

    CONSTRAINT "bills_pkey" PRIMARY KEY ("invoice_no")
);

-- CreateIndex
CREATE INDEX "bills_claim_no_idx" ON "bills"("claim_no");

-- CreateIndex
CREATE INDEX "bills_member_no_idx" ON "bills"("member_no");

-- CreateIndex
CREATE INDEX "bills_provider_idx" ON "bills"("provider");

-- CreateIndex
CREATE INDEX "bills_batch_no_idx" ON "bills"("batch_no");
